export default {
    login: "LOGIN",
    register: "REGISTER" ,
    addProject: "ADD_PROJECT",
    getProjects: "GET_PROJECTS",
    fileUpload:"FILE_UPLOAD",
    getFiles:"GET_FILES",
    logout:"LOGOUT",
    verified:"VERIFIED",
    getUser:"GET_USER",
    getVersions:"GET_VERSIONS",
    getUserName:"GET_USERNAME",
    verified:"VERIFIED",
    restoreVersion:"RESTORE_VERSION",
    getMessages:"GET_MESSAGES",
    getAllProjects:"GET_ALL_PROJECTS",
    getContributions:"GET_CONTRIBUTIONS",
    starProject:"STAR_PROJECT",
    unstarProject:"UNSTAR_PROJECT",
    getProject:"GET_PROJECT",
    isStarred:"IS_STARRED",
    numberOfContributorsPerProject:"NUMBER_OF_CONTRIBUTORS_PER_PROJECT",
    numberOfStarsPerProject:"NUMBER_OF_STARS_PER_PROJECT",
    changePassword:"CHANGE_PASSWORD",
    getSkills:"GET_SKILLS",
    getUserSkills:"GET_USER_SKILLS",
    getProfile:"GET_PROFILE",
    updateProfile:"UPDATE_PROFILE",
    addToForum: "ADD_TO_FORUM",
    getForumPosts: "GET_FORUM_POSTS",
    addFileToForum:"ADD_FILE_TO_FORUM",
    getForumPost:"GET_FORUM_POST",
    upvote:"UPVOTE",
    downvote:"DOWNVOTE",
    isUpvoted:"IS_UPVOTED",
    isDownvoted:"IS_DOWNVOTED",
    deleteFile:"DELETE_FILE"
}