export default {
    login: "LOGIN",
    register: "REGISTER" ,
    addProject: "ADD_PROJECT",
    getProjects: "GET_PROJECTS",
    fileUpload:"FILE_UPLOAD",
    getFiles:"GET_FILES",
    logout:"LOGOUT",
    verified:"VERIFIED",
    getUser:"GET_USER",
    getVersions:"GET_VERSIONS",
    getUserName:"GET_USERNAME",
    verified:"VERIFIED",
    restoreVersion:"RESTORE_VERSION",
    getMessages:"GET_MESSAGES",
    getAllProjects:"GET_ALL_PROJECTS",
    getContributions:"GET_CONTRIBUTIONS",
    starProject:"STAR_PROJECT",
    unstarProject:"UNSTAR_PROJECT",
    getProject:"GET_PROJECT",
    isStarred:"IS_STARRED",
    numberOfContributorsPerProject:"NUMBER_OF_CONTRIBUTORS_PER_PROJECT",
    numberOfStarsPerProject:"NUMBER_OF_STARS_PER_PROJECT"
}